apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: default  # Ensure the correct namespace is specified or default if no specific namespace is required
  labels:
    app: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: muyiwao/flask-api:latest
  ports:
    - containerPort: 5310
  env:
    - name: ENDPOINT
      value: "${DB_ENDPOINT}"
    - name: USER
      value: "${DB_USER}"
    - name: PASSWORD
      value: "${DB_PASSWORD}"
    - name: PORT
      value: "${DB_PORT}"
    - name: DATABASE
      value: "${DB_NAME}"
